# permissions to do viewer ebssnaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ebssnap-viewer-role
rules:
- apiGroups:
  - exoapps.github.com/ajit009/ebs-snap-pv.git
  resources:
  - ebssnaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - exoapps.github.com/ajit009/ebs-snap-pv.git
  resources:
  - ebssnaps/status
  verbs:
  - get
